### ISSUE TITLE
Looking to adopt this plugin

### ISSUE THREAD

**Issue by Aida-Enna** [CallumCarmicheal/XIVControllerToggle#1]
Heya! I saw a few users asking about this plugin you made and saw it hasn't been updated in a bit - Are you still actively working on it? If not, I'd like to adopt it and update it for DT

**Comment by CallumCarmicheal** [comment]
Hello Aida,

Thanks for the interest. I did update the plugin to the latest version for Dawntrial but I forgot to push the changes nor put in the pull request. 

I've added you as a contributor to the repository as I've been busy these past 2 weeks without a chance to really check the backlog of notifications.

I'll push out the update within a few hours, gotta clean up the code.

Thanks,
Callum
