### ISSUE TITLE
Unable to select other layouts for controller

### ISSUE THREAD

**Issue by StackBLU** [CallumCarmicheal/XIVControllerToggle#3]
When I click 2 3 or 4, nothing changes. I can change it for keyboard, but not controller.

![30af4a4e09e0f75d58b1ad0a165cf02b](https://github.com/user-attachments/assets/d01ac6c7-5434-48d7-9d57-ba4adf5bfbc2)

**Comment by CallumCarmicheal** [comment]
Thanks for the heads up @StackBLU, I have resolved the issue and should have the update out soon.

**Comment by CallumCarmicheal** [comment]
Forgot to update this issue, I had pushed out a fix for this awhile back, closing issue.
