### ISSUE TITLE
Option to hide/unhide chat panel on switch

### ISSUE THREAD

**Issue by AkazaRenn** [CallumCarmicheal/XIVControllerToggle#4]
It's quite confusing that the chat panel isn't managed by the HUD. Would it be possible to have an option to hide the chat panel under one input and unhide on another?

**Comment by CallumCarmicheal** [comment]
@AkazaRenn That's a pretty good idea, I've been working on a new version to allow for deeper customisation and will look into implementing this. It's taking some time as lately not really had much time free to work on it. Will keep you posted on it.

**Comment by CallumCarmicheal** [comment]
Sorry its taken awhile to get an update towards this, I am still looking into the correct way to hide the chat element. The current system I have will permantly hide the chat by disabling it's object from rendering instead of the "Hide Log Window" functionality where you could pop the chat back open on a keypress. 

I'll keep you posted, hopefully should find a solution later today.

**Comment by AkazaRenn** [comment]
> Sorry its taken awhile to get an update towards this, I am still looking into the correct way to hide the chat element. The current system I have will permantly hide the chat by disabling it's object from rendering instead of the "Hide Log Window" functionality where you could pop the chat back open on a keypress. 
> 
> I'll keep you posted, hopefully should find a solution later today.

It's totally fine! Please feel free to take your time, I'm greatly appreciated to your help!

**Comment by CallumCarmicheal** [comment]
> It's totally fine! Please feel free to take your time, I'm greatly appreciated to your help!

Good news, thanks to @Haselnussbomber I was able to figure out how to do it and pushed the change. If I didn't mess up the pull request again it should be out today at some point :)

**Comment by AkazaRenn** [comment]
@CallumCarmicheal that would be awesome!! Thanks again for it!

**Comment by CallumCarmicheal** [comment]
> @CallumCarmicheal that would be awesome!! Thanks again for it!

The changes have been merged into the plugin repository, the update should now be available.
https://github.com/goatcorp/DalamudPluginsD17/pull/5069
