### ISSUE TITLE
API Update Required

### ISSUE THREAD

**Issue by 2dchaos** [CallumCarmicheal/XIVControllerToggle#5]
Hi! There has been an update on Dalamud for 7.1, so I think you'll need to make some changes to keep the plugin compatible. Thanks for your work, really makes our lifes easier. :)

**Comment by CallumCarmicheal** [comment]
Hello @2dchaos 

Thanks for the support, I have pushed the updated version to the plugin repostiory. Just waiting for a reviewer to take a peek.
https://github.com/goatcorp/DalamudPluginsD17/pull/5069

😄

**Comment by CallumCarmicheal** [comment]
Changes were merged into the plugin repository. The update is now available.
